### PR TITLE
Fix preffered nick list out of bound

### LINKED ISSUE #10: Selected item background in "Preferred nicks" list is out of bounds

### PR DESCRIPTION
**Pull request by raefaldhia**
Fix selected item in preffered nick list that out of bound.

Fixes #10

See ListView that contains name Haikuuser & raefaldhia
Left: **Before**
RIght: **After**
screenshot from 2016-12-07 13-22-28

### CODE REVIEW

**Comment by waddlesplash** [comment]
Link to GCI task please.

**Comment by raefaldhia** [comment]
@waddlesplash https://codein.withgoogle.com/dashboard/task-instances/5157138429116416/
@pulkomandy sorry, I'll describe later because i need to go to school now.

**Comment by pulkomandy** [comment]
Thanks. It does not seem right to just remove 4 pixels this way. I would prefer to know where the error comes from and why there is an offset in the first place.

**Comment by raefaldhia** [comment]
@pulkomandy do you know what's version of commit for vision inside haiku nightly build? because that app doesn't contain #10 and #9 so that will make me easier to find out what's the problem between the oldest commit and newer one that produce this bug.

**Comment by raefaldhia** [comment]
After some hours analyzing this issue just found out that https://github.com/HaikuArchives/Vision/blob/master/src/NetworkPrefsView.cpp#L262 caused the bug, idk what the code supposed to do because without it, vision running fine without #10.

**Pull request merged**
