### PR TITLE
Experimental

### LINKED ISSUE #1: Not all URLs in the topic of a channel are clickable
For some reason not all URLs in the topic of a channel are clickable.   

The clickable URLs seem to be displayed with a proportional font, the non-clickable are fixed-width.

### LINKED ISSUE #6: Prettify Preferences window
Make it look a bit more like Tracker settings window, i.e. the insets.

### LINKED ISSUE #7: Use default resize cursor
...and maybe splitter too?

### LINKED ISSUE #13: Change Vison to use the layout api

### PR DESCRIPTION
**Pull request by janus2**
## WIP Please test and report!

Introducing Layout
- Fixes #1 
- Fixes #6  
- Fixes #7 
- Fixes #13

### CODE REVIEW

**Comment by waddlesplash** [comment]
Looks good.

You can probably drop all of the commented-out code, of course.

**Comment by janus2** [comment]
Yes I'll wait for the feedbacks from @humdingerb and vidrep.

**Comment by janus2** [comment]
I hate this triangle
rectangle

This is the latch with the status color, very hackerish

latchstatus

**Comment by diversys** [comment]
I tested Vision and found this bug with this PR applied #36. Also crashes on quit in BMenu code.

**Comment by janus2** [comment]
The crash on quit is present even in the current version if you open a channel list. Fixed some causes but not all.

**Comment by humdingerb** [comment]
Looks and work good! Nice work!
Two things I see:

1. In the various preference views, there should be a Glue() or something to keep all elements at the top when the window is resized vertically.
2. There's a double border to the left and bottom of the window/notify list: https://postimg.cc/image/h8z3om2cx/

**Comment by janus2** [comment]
Thanks!
1. Yes The preference views need some tuning...
2. It's not a doble border is the border of the ScrollView and the line of the StatusBar there is not spacing between... This can be solve with a negative inset, but the same problem is present under the name list and that is very hard to remove.

**Pull request merged**
