### PR TITLE
Add layout to Network prefs

### PR DESCRIPTION
**Pull request by janus2**
### WIP PLEASE DON'T MERGE. [RFC]

### CODE REVIEW

**Comment by janus2** [comment]
### Not layout version

networkprefsoriginal

### Current PR

networkprefspr

### With +/- buttons

networkprefrepobuttons

**Comment by pulkomandy** [comment]
On Wed, Jul 25, 2018 at 10:33:34AM -0700, janus2 wrote:
> ### Not layout version
> 
> networkprefsoriginal
> 
> ### Current PR
> 
> networkprefspr
> 
> ### With +/- buttons
> 
> networkprefrepobuttons
 
I hate nested BBoxes. How about this:
http://pulkomandy.tk/drop/visionprefs.png

**Comment by jscipione** [comment]
Nice work. I have 2 suggestions if you're up for it.

First drop the Nested BBoxes like PulkoMandy suggested, you can remove the line with: SetBorder(B_NO_BORDER);

Second update preferred nicks to use a separate textview and listview with plus and minus on the right of to each respectively like in Network Time tab of Time Prefs: https://www.haiku-os.org/docs/userguide/en/images/prefs-images/time-network.png

**Comment by janus2** [comment]
The result with B_NO_BORDER is this:

noborder

**Comment by janus2** [comment]
I think for @pulkomandy solution a BSeparatorView is needed.

**Comment by jscipione** [comment]
That looks pretty ok to me just need to reduce the window margins, try:
SetInsets(0, B_USE_SMALL_SPACING, 0, B_USE_SMALL_SPACING)
(small on top and bottom, 0 on left and right) i'm thinking you'll want some bottom spacing for the checkbox. you may need to tweak to look ok.

**Comment by janus2** [comment]
@pulkomandy idea:

pulkomandy

**Comment by waddlesplash** [comment]
Nice!

**Comment by jscipione** [comment]
Really close just get the left and right margins to match the magic s between the boxes try B_SMALL_MARGINS on all sides sry to backseat develop

**Comment by janus2** [comment]
> Really close just get the left and right margins to match the margins between the boxes try B_USE_SMALL_SPACING on all sides sry to backseat develop

It is on purpose. I want the menuField aligned with the BBox...

**Comment by janus2** [comment]
The difference is minimal, but the menu and the BBox are unaligned

with small_spacing

**Comment by jscipione** [comment]
Maybe B_USE_DEFAULT_SPACING on left and right then, then use a negative left Inset on the BMenuField control child of the BBox to align it with the checkbox again... I'm not sure if that that will work... either way it looks much better than the Vision Network Windows I'm used to seeing!

**Comment by janus2** [comment]
I just look into the code of BSeparatorView the offset is fixed at 5px this is not very good...

**Comment by janus2** [comment]
Using the BBox the offset pixels are 8 a little better.

**Comment by janus2** [comment]
### Without Layout

original


### With Layout

layout

**Comment by scottmc** [comment]
in the layout version, is the alternating white/grey background pattern still there for the servers view and just not shown in the image because you only had one showing?

**Comment by janus2** [comment]
> in the layout version, is the alternating white/grey background pattern still there for the servers view and just not shown in the image because you only had one showing?

Even if you want you cannot remove that pattern...

**Comment by janus2** [comment]
>Second update preferred nicks to use a separate textview and listview with plus and minus on the right of to each respectively like in Network Time tab of Time Prefs: https://www.haiku-os.org/docs/userguide/en/images/prefs-images/time-network.png

@jscipione  I like the idea, but the same window is used to add a Network so I prefer consistency.

**Pull request merged**
