### PR TITLE
add screenshot

### PR DESCRIPTION
**Pull request by ayushmunot**

### CODE REVIEW

**Comment by diversys** [comment]
screenshot points to ayushmunot account.

**Comment by ayushmunot** [comment]
I didn't get what you want to say. Clicking the image leads to the image that I uploaded in the repository.

**Comment by diversys** [comment]
The link should point to HaikuArchives. Right now it points to your fork:
+Vision App

**Comment by ayushmunot** [comment]
Is it fine now?

**Comment by ayushmunot** [comment]
https://github.com/HaikuArchives/Vision/pull/29

**Pull request merged**
